# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1anSv2bWAsm_JR4IqieeThXz-T-y__iGG
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('df.csv')

df

df.info()

df.columns

del df['Size']

df

df.info()

df.drop('Rating', 1)

df.info()

